### ISSUE TITLE
Addin stopped working since RStudio upgrade

### ISSUE THREAD

**Issue by mj-ramirez** [gadenbuie/regexplain#23] opened 2021-02-05 10:41 UTC
Only the "Cheatsheeth" does launch despite the error message

> regexplain:::regexplain_addin()
Error in get(x, envir = ns, inherits = FALSE) : object '%AND%' not found

RStudio
Version 1.4.1103

MacBook-Air M1
 r --version
R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

**Comment by gadenbuie** [comment] 2021-02-05 12:08
Duplicate of #22 ... Please update regexplain for the fix.

**Closed** 2021-02-05 12:15 UTC

**Comment by mj-ramirez** [comment] 2021-02-05 14:46
Ok
